/**
 * @file error_code.h
 * @brief 慧仓智控设备端错误码定义（AUTO-GENERATED BY tools/gen/gen-errorcodes.ps1 — DO NOT EDIT）
 *
 * 唯一来源：WiseDeoptServer/wise-depot-plan/后端异常码对照表.csv
 * 名称与顺序来源：tools/gen/errorcode-manifest.json
 */
#ifndef WISE_DEPOT_COMMON_ERROR_CODE_H
#define WISE_DEPOT_COMMON_ERROR_CODE_H

#ifdef __cplusplus
extern "C" {
#endif

/** 错误码信息表项：错误码、中文描述、HTTP 语义状态码 */
typedef struct {
    const char *code;        /**< 错误码，如 "AUTH-REQUEST-1001" */
    const char *message;     /**< 中文描述 */
    int         http_status; /**< 对应的 HTTP 状态码 */
} wd_error_info_t;

/* ===== 错误码宏定义（与三端保持一致）===== */
#define WD_SUCCESS                                "RES-0000"
#define WD_PARAM_ERROR                            "VAL-0001"
#define WD_NOT_FOUND                              "RES-0004"
#define WD_UNAUTHORIZED                           "AUTH-0001"
#define WD_AUTH_INVALID_TOKEN                     "AUTH-0002"
#define WD_AUTH_TOKEN_EXPIRED                     "AUTH-0003"
#define WD_AUTH_REFRESH_TOKEN_INVALID             "AUTH-0004"
#define WD_FORBIDDEN                              "AUTH-0005"
#define WD_SYSTEM_ERROR                           "SYS-0001"
#define WD_REQUEST_NOT_FOUND                      "RES-REQUEST-1001"
#define WD_REQUEST_METHOD_NOT_ALLOWED             "RES-REQUEST-1002"
#define WD_REQUEST_ID_MISSING                     "RES-REQUEST-1004"
#define WD_SYSTEM_REQUEST_ERROR                   "SYS-REQUEST-1001"
#define WD_AUTH_REQUEST_NO_IP                     "AUTH-REQUEST-1001"
#define WD_AUTH_REQUEST_USERNAME_PASSWORD_ERROR   "AUTH-REQUEST-1002"
#define WD_AUTH_REQUEST_EMAIL_PASSWORD_ERROR      "AUTH-REQUEST-1003"
#define WD_AUTH_REQUEST_NFC_NOT_FOUND             "AUTH-REQUEST-1004"
#define WD_AUTH_REQUEST_VERIFICATION_ID_INVALID   "AUTH-REQUEST-1005"
#define WD_AUTH_REQUEST_PIN_ERROR                 "AUTH-REQUEST-1006"
#define WD_AUTH_REQUEST_REFRESH_TOKEN_INVALID     "AUTH-REQUEST-1007"
#define WD_AUTH_REQUEST_PASSWORD_VERIFY_FAILED    "AUTH-REQUEST-1008"
#define WD_AUTH_REQUEST_TOKEN_PARSE_FAILED        "AUTH-REQUEST-1009"
#define WD_AUTH_REQUEST_TOKEN_EMPTY               "AUTH-REQUEST-1010"
#define WD_AUTH_REQUEST_TOKEN_EXPIRED             "AUTH-REQUEST-1011"
#define WD_AUTH_ACCOUNT_DISABLED                  "AUTH-ACCOUNT-1001"
#define WD_AUTH_ACCOUNT_LOCKED                    "AUTH-ACCOUNT-1002"
#define WD_VAL_REQUEST_BODY_INVALID               "VAL-REQUEST-1001"
#define WD_VAL_REQUEST_OSS_NO_FILE                "VAL-REQUEST-OSS-1001"
#define WD_VAL_REQUEST_OSS_FILE_EMPTY             "VAL-REQUEST-OSS-1002"
#define WD_VAL_PARAM_AUTH_LOGIN_TYPE_EMPTY        "VAL-PARAM-AUTH-1001"
#define WD_VAL_RANGE_AUTH_LOGIN_TYPE_ERROR        "VAL-RANGE-AUTH-1001"
#define WD_VAL_PARAM_AUTH_USERNAME_EMPTY          "VAL-PARAM-AUTH-1002"
#define WD_VAL_PARAM_AUTH_EMAIL_EMPTY             "VAL-PARAM-AUTH-1003"
#define WD_VAL_PARAM_AUTH_PASSWORD_EMPTY          "VAL-PARAM-AUTH-1004"
#define WD_VAL_FORMAT_AUTH_EMAIL_ERROR            "VAL-FORMAT-AUTH-1001"
#define WD_VAL_PARAM_AUTH_CARD_UUID_EMPTY         "VAL-PARAM-AUTH-1005"
#define WD_VAL_PARAM_AUTH_VERIFICATION_ID_EMPTY   "VAL-PARAM-AUTH-1006"
#define WD_VAL_PARAM_AUTH_PIN_EMPTY               "VAL-PARAM-AUTH-1007"
#define WD_VAL_PARAM_AUTH_ACCESS_TOKEN_EMPTY      "VAL-PARAM-AUTH-1008"
#define WD_VAL_PARAM_AUTH_CAPTCHA_ID_EMPTY        "VAL-PARAM-AUTH-1009"
#define WD_VAL_PARAM_AUTH_CAPTCHA_CODE_EMPTY      "VAL-PARAM-AUTH-1010"
#define WD_VAL_FORMAT_AUTH_CARD_UUID_ERROR        "VAL-FORMAT-AUTH-1002"
#define WD_VAL_PARAM_USER_ID_EMPTY                "VAL-PARAM-USER-1001"
#define WD_VAL_PARAM_USER_PASSWORD_EMPTY          "VAL-PARAM-USER-1002"
#define WD_VAL_RANGE_OSS_EXPIRES_OUT_OF_RANGE     "VAL-RANGE-OSS-1001"
#define WD_SYS_IO_OSS_SERVICE_UNAVAILABLE         "SYS-IO-OSS-1001"
#define WD_SYS_IO_OSS_PRESIGN_ERROR               "SYS-IO-OSS-1002"
#define WD_SYS_IO_OSS_STAT_ERROR                  "SYS-IO-OSS-1003"
#define WD_SYS_IO_OSS_UPLOAD_ERROR                "SYS-IO-OSS-1004"
#define WD_SYS_IO_OSS_DELETE_ERROR                "SYS-IO-OSS-1005"

/**
 * @brief 按错误码查表取信息。
 * @param code 错误码字符串，可为 NULL
 * @return 匹配到的表项；未匹配时返回 NULL
 */
const wd_error_info_t *wd_error_lookup(const char *code);

/**
 * @brief 取错误码的中文描述。
 * @param code 错误码字符串，可为 NULL
 * @return 描述字符串；未匹配时返回 "未知错误"
 */
const char *wd_error_message(const char *code);

/**
 * @brief 判断错误码是否表示成功。
 * @param code 错误码字符串，可为 NULL
 * @return 1 表示成功，0 表示失败
 */
int wd_error_is_success(const char *code);

/* 成功错误码，单独提供便于比较 */
#define WD_ERROR_SUCCESS "RES-0000"

#ifdef __cplusplus
}
#endif

#endif /* WISE_DEPOT_COMMON_ERROR_CODE_H */
