/**
 * @file error_code.c
 * @brief 设备端错误码查表实现（AUTO-GENERATED BY tools/gen/gen-errorcodes.ps1 — DO NOT EDIT）
 */
#include <string.h>

#include "common/error_code.h"

/** 错误码表，顺序与 tools/gen/errorcode-manifest.json 一致 */
static const wd_error_info_t WD_ERROR_TABLE[] = {
    { WD_SUCCESS                            , "处理成功", 200 },
    { WD_PARAM_ERROR                        , "请求参数不合法", 400 },
    { WD_NOT_FOUND                          , "资源不存在", 404 },
    { WD_UNAUTHORIZED                       , "未认证或登录状态已失效", 401 },
    { WD_AUTH_INVALID_TOKEN                 , "无效的访问令牌", 401 },
    { WD_AUTH_TOKEN_EXPIRED                 , "访问令牌已过期", 419 },
    { WD_AUTH_REFRESH_TOKEN_INVALID         , "刷新令牌已失效", 401 },
    { WD_FORBIDDEN                          , "无访问权限", 403 },
    { WD_SYSTEM_ERROR                       , "系统内部错误，请稍后重试", 500 },
    { WD_REQUEST_NOT_FOUND                  , "接口不存在", 404 },
    { WD_REQUEST_METHOD_NOT_ALLOWED         , "请求方法不可用", 405 },
    { WD_REQUEST_ID_MISSING                 , "请求时未携带REQUEST-ID", 500 },
    { WD_SYSTEM_REQUEST_ERROR               , "未知异常", 500 },
    { WD_AUTH_REQUEST_NO_IP                 , "未检测到用户IP地址", 403 },
    { WD_AUTH_REQUEST_USERNAME_PASSWORD_ERROR, "用户名或密码错误", 401 },
    { WD_AUTH_REQUEST_EMAIL_PASSWORD_ERROR  , "邮箱或密码错误", 401 },
    { WD_AUTH_REQUEST_NFC_NOT_FOUND         , "工牌不存在或已失效", 401 },
    { WD_AUTH_REQUEST_VERIFICATION_ID_INVALID, "二步验证id无效或已过期", 401 },
    { WD_AUTH_REQUEST_PIN_ERROR             , "PIN码不匹配", 401 },
    { WD_AUTH_REQUEST_REFRESH_TOKEN_INVALID , "刷新令牌已失效", 401 },
    { WD_AUTH_REQUEST_PASSWORD_VERIFY_FAILED, "密码校验失败", 401 },
    { WD_AUTH_REQUEST_TOKEN_PARSE_FAILED    , "访问令牌解析失败", 401 },
    { WD_AUTH_REQUEST_TOKEN_EMPTY           , "访问令牌为空", 401 },
    { WD_AUTH_REQUEST_TOKEN_EXPIRED         , "访问令牌已过期", 419 },
    { WD_AUTH_ACCOUNT_DISABLED              , "账户状态异常", 403 },
    { WD_AUTH_ACCOUNT_LOCKED                , "账户状态异常（短时间登录失败次数过多被锁定）", 429 },
    { WD_VAL_REQUEST_BODY_INVALID           , "请求体解析失败", 400 },
    { WD_VAL_REQUEST_OSS_NO_FILE            , "未检测到上传文件", 400 },
    { WD_VAL_REQUEST_OSS_FILE_EMPTY         , "文件内容为空", 422 },
    { WD_VAL_PARAM_AUTH_LOGIN_TYPE_EMPTY    , "loginType字段为空", 422 },
    { WD_VAL_RANGE_AUTH_LOGIN_TYPE_ERROR    , "loginType字段范围错误", 422 },
    { WD_VAL_PARAM_AUTH_USERNAME_EMPTY      , "username字段为空", 422 },
    { WD_VAL_PARAM_AUTH_EMAIL_EMPTY         , "email字段为空", 422 },
    { WD_VAL_PARAM_AUTH_PASSWORD_EMPTY      , "password字段为空", 422 },
    { WD_VAL_FORMAT_AUTH_EMAIL_ERROR        , "email格式错误", 422 },
    { WD_VAL_PARAM_AUTH_CARD_UUID_EMPTY     , "cardUuid字段为空", 422 },
    { WD_VAL_PARAM_AUTH_VERIFICATION_ID_EMPTY, "verificationId字段为空", 422 },
    { WD_VAL_PARAM_AUTH_PIN_EMPTY           , "pin字段为空", 422 },
    { WD_VAL_PARAM_AUTH_ACCESS_TOKEN_EMPTY  , "accessToken字段为空", 422 },
    { WD_VAL_PARAM_AUTH_CAPTCHA_ID_EMPTY    , "captchaId字段为空", 422 },
    { WD_VAL_PARAM_AUTH_CAPTCHA_CODE_EMPTY  , "captchaCode字段为空", 422 },
    { WD_VAL_FORMAT_AUTH_CARD_UUID_ERROR    , "cardUuid格式错误", 422 },
    { WD_VAL_PARAM_USER_ID_EMPTY            , "userId字段为空", 422 },
    { WD_VAL_PARAM_USER_PASSWORD_EMPTY      , "password字段为空", 422 },
    { WD_VAL_RANGE_OSS_EXPIRES_OUT_OF_RANGE , "MinIO临时访问链接有效期超出范围", 422 },
    { WD_SYS_IO_OSS_SERVICE_UNAVAILABLE     , "文件存储服务不可用或连接异常", 503 },
    { WD_SYS_IO_OSS_PRESIGN_ERROR           , "获取MinIO临时访问链接异常", 500 },
    { WD_SYS_IO_OSS_STAT_ERROR              , "获取MinIO文件状态异常", 500 },
    { WD_SYS_IO_OSS_UPLOAD_ERROR            , "上传文件到MinIO失败", 500 },
    { WD_SYS_IO_OSS_DELETE_ERROR            , "删除MinIO文件失败", 500 },
    { WD_VAL_CONFLICT_PERMISSION_CODE_EXISTS, "权限编码已存在", 409 },
};

const wd_error_info_t *wd_error_lookup(const char *code) {
    size_t i;

    if (code == NULL) {
        return NULL;
    }

    for (i = 0; i < sizeof(WD_ERROR_TABLE) / sizeof(WD_ERROR_TABLE[0]); i++) {
        if (strcmp(WD_ERROR_TABLE[i].code, code) == 0) {
            return &WD_ERROR_TABLE[i];
        }
    }

    return NULL;
}

const char *wd_error_message(const char *code) {
    const wd_error_info_t *info = wd_error_lookup(code);

    return (info != NULL) ? info->message : "未知错误";
}

int wd_error_is_success(const char *code) {
    if (code == NULL) {
        return 0;
    }

    return (strcmp(code, WD_ERROR_SUCCESS) == 0) ? 1 : 0;
}
